export interface Influencer {
  id: number
  name: string
  niche: string
  followers: string
  followersNum: number
  platform: string
  avatar: string
  avatarBg: string
  profileImage: string
  engagement: string
  location: string
  bio: string
  tags: string[]
  verified: boolean
  campaigns: number
  trending?: boolean
}

export interface CollabRequest {
  id: number
  campaignName: string
  brand: string
  influencer: string
  budget: string
  date: string
  status: "Pending" | "Accepted" | "Declined"
}

export const influencers: Influencer[] = [
  {
    id: 1,
    name: "Technical Guruji",
    niche: "Tech",
    followers: "23.8M",
    followersNum: 23800000,
    platform: "YouTube",
    avatar: "TG",
    avatarBg: "#E94560",
    profileImage: "https://yt3.googleusercontent.com/ytc/AIdro_kSFMkMaSwzpnBqmT0Ik93GEjCFm-F6MeTRSJTi8g=s176-c-k-c0x00ffffff-no-rj",
    engagement: "3.2%",
    location: "Delhi",
    bio: "India's #1 tech YouTuber delivering gadget reviews, unboxings, and technology news in Hindi to millions of viewers.",
    tags: ["Tech Reviews", "Gadgets", "Unboxing"],
    verified: true,
    campaigns: 120,
    trending: true,
  },
  {
    id: 2,
    name: "Komal Pandey",
    niche: "Fashion",
    followers: "2.1M",
    followersNum: 2100000,
    platform: "Instagram",
    avatar: "KP",
    avatarBg: "#A855F7",
    profileImage: "https://i.pravatar.cc/300?img=47",
    engagement: "5.8%",
    location: "Delhi",
    bio: "Fashion & lifestyle content creator known for bold styling, trend-setting looks, and body-positive fashion inspiration.",
    tags: ["Street Style", "Trends", "Body Positivity"],
    verified: true,
    campaigns: 85,
    trending: true,
  },
  {
    id: 3,
    name: "Beer Biceps",
    niche: "Fitness",
    followers: "8.2M",
    followersNum: 8200000,
    platform: "YouTube",
    avatar: "BB",
    avatarBg: "#00B4D8",
    profileImage: "https://yt3.googleusercontent.com/ytc/AIdro_lLz36EC3h0kLTpRPv9jVoaNhkJJGdDxKceWJAl=s176-c-k-c0x00ffffff-no-rj",
    engagement: "4.5%",
    location: "Mumbai",
    bio: "Ranveer Allahbadia — fitness, mindset & entrepreneurship content. Host of India's top podcasts on health and self-improvement.",
    tags: ["Fitness", "Podcast", "Mindset"],
    verified: true,
    campaigns: 95,
    trending: true,
  },
  {
    id: 4,
    name: "Kabita Singh",
    niche: "Food",
    followers: "14.5M",
    followersNum: 14500000,
    platform: "YouTube",
    avatar: "KS",
    avatarBg: "#FF9F43",
    profileImage: "https://yt3.googleusercontent.com/ytc/AIdro_ks0t3W3vcJFQn8y8s5w5n4ppxclON_eK_r7VJ2=s176-c-k-c0x00ffffff-no-rj",
    engagement: "6.1%",
    location: "Noida",
    bio: "Kabita's Kitchen — India's most-loved food channel with easy home cooking recipes, street food recreations, and festival specials.",
    tags: ["Home Cooking", "Indian Recipes", "Street Food"],
    verified: true,
    campaigns: 68,
    trending: true,
  },
  {
    id: 5,
    name: "Larissa D'Sa",
    niche: "Travel",
    followers: "503K",
    followersNum: 503000,
    platform: "Instagram",
    avatar: "LD",
    avatarBg: "#10B981",
    profileImage: "https://i.pravatar.cc/300?img=32",
    engagement: "5.9%",
    location: "Goa",
    bio: "Travel blogger and photographer exploring hidden gems across India and Southeast Asia. Known for curated aesthetic travel guides.",
    tags: ["Budget Travel", "Photography", "Hidden Gems"],
    verified: true,
    campaigns: 42,
    trending: true,
  },
  {
    id: 6,
    name: "Sejal Kumar",
    niche: "Fashion",
    followers: "1.3M",
    followersNum: 1300000,
    platform: "Instagram",
    avatar: "SK",
    avatarBg: "#EC4899",
    profileImage: "https://i.pravatar.cc/300?img=23",
    engagement: "4.7%",
    location: "Delhi",
    bio: "Fashion, lifestyle & music creator blending Indian aesthetics with global trends. Singer-songwriter and style icon.",
    tags: ["Ethnic Wear", "Lifestyle", "Music"],
    verified: true,
    campaigns: 73,
    trending: true,
  },
  {
    id: 7,
    name: "CA Rachana Ranade",
    niche: "Finance",
    followers: "5.6M",
    followersNum: 5600000,
    platform: "YouTube",
    avatar: "RR",
    avatarBg: "#3B82F6",
    profileImage: "https://yt3.googleusercontent.com/ytc/AIdro_m8cMf8UgGDw-c5K2d_BYeyRFJrNH7hVnBJ3tRD=s176-c-k-c0x00ffffff-no-rj",
    engagement: "4.2%",
    location: "Pune",
    bio: "CA & finance educator simplifying stock markets, mutual funds, and personal finance for India's young investors.",
    tags: ["Stock Market", "Mutual Funds", "Financial Literacy"],
    verified: true,
    campaigns: 35,
    trending: false,
  },
  {
    id: 8,
    name: "Shilpa Shetty",
    niche: "Wellness",
    followers: "28.5M",
    followersNum: 28500000,
    platform: "Instagram",
    avatar: "SS",
    avatarBg: "#14B8A6",
    profileImage: "https://i.pravatar.cc/300?img=44",
    engagement: "3.1%",
    location: "Mumbai",
    bio: "Actress, entrepreneur & wellness advocate. Shares yoga routines, Ayurvedic health tips, and mindful living content.",
    tags: ["Yoga", "Ayurveda", "Healthy Living"],
    verified: true,
    campaigns: 55,
    trending: true,
  },
  {
    id: 9,
    name: "Mumbiker Nikhil",
    niche: "Travel",
    followers: "4.1M",
    followersNum: 4100000,
    platform: "YouTube",
    avatar: "MN",
    avatarBg: "#EF4444",
    profileImage: "https://yt3.googleusercontent.com/ytc/AIdro_lJ2jQ5dEJ-v7x3rBT7e18g7A4uc5ew5EMHXMC3=s176-c-k-c0x00ffffff-no-rj",
    engagement: "4.8%",
    location: "Mumbai",
    bio: "India's favourite motovlogger turned travel & lifestyle creator. Daily vlogs covering road trips, tech, and real-life adventures.",
    tags: ["Motovlogging", "Road Trips", "Daily Vlogs"],
    verified: true,
    campaigns: 88,
    trending: true,
  },
  {
    id: 10,
    name: "Nykaa Beauty",
    niche: "Beauty",
    followers: "3.8M",
    followersNum: 3800000,
    platform: "TikTok",
    avatar: "NB",
    avatarBg: "#FF6B81",
    profileImage: "https://i.pravatar.cc/300?img=5",
    engagement: "7.2%",
    location: "Mumbai",
    bio: "Official beauty content from India's leading beauty platform. Quick tutorials, product drops, and trending beauty hacks.",
    tags: ["Beauty Hacks", "Makeup", "Skincare"],
    verified: true,
    campaigns: 150,
    trending: true,
  },
  {
    id: 11,
    name: "Sahil Khan",
    niche: "Fitness",
    followers: "11.2M",
    followersNum: 11200000,
    platform: "Facebook",
    avatar: "SK",
    avatarBg: "#1877F2",
    profileImage: "https://i.pravatar.cc/300?img=52",
    engagement: "4.5%",
    location: "Mumbai",
    bio: "Fitness icon and entrepreneur inspiring millions with transformation journeys, workout routines, and supplement guidance.",
    tags: ["Bodybuilding", "Transformation", "Supplements"],
    verified: true,
    campaigns: 62,
    trending: true,
  },
  {
    id: 12,
    name: "Bhuvan Bam",
    niche: "Entertainment",
    followers: "27M",
    followersNum: 27000000,
    platform: "YouTube",
    avatar: "BB",
    avatarBg: "#F97316",
    profileImage: "https://yt3.googleusercontent.com/ytc/AIdro_nLaQoqpd0lUZoXGU-B9KR9GNx3OPXO7s_IKyNEjQ=s176-c-k-c0x00ffffff-no-rj",
    engagement: "5.3%",
    location: "Delhi",
    bio: "India's most-subscribed individual creator. Comedian, musician, and actor known for BB Ki Vines and Taaza Khabar.",
    tags: ["Comedy", "Music", "Acting"],
    verified: true,
    campaigns: 105,
    trending: true,
  },
]

export const niches = [
  "All",
  "Tech",
  "Beauty",
  "Fitness",
  "Food",
  "Travel",
  "Fashion",
  "Wellness",
  "Finance",
  "Entertainment",
]

export const platforms = ["All", "Instagram", "YouTube", "TikTok", "Facebook"]

export const followerRanges = [
  { label: "All", min: 0, max: Infinity },
  { label: "Nano (1K-10K)", min: 1000, max: 10000 },
  { label: "Micro (10K-100K)", min: 10000, max: 100000 },
  { label: "Mid (100K-500K)", min: 100000, max: 500000 },
  { label: "Macro (500K+)", min: 500000, max: Infinity },
]

export const sampleRequests: CollabRequest[] = [
  {
    id: 1,
    campaignName: "Summer Tech Launch",
    brand: "TechVista India",
    influencer: "Technical Guruji",
    budget: "\u20B92,50,000",
    date: "2026-02-15",
    status: "Accepted",
  },
  {
    id: 2,
    campaignName: "Glow Up Series",
    brand: "NaturaBright",
    influencer: "Komal Pandey",
    budget: "\u20B91,50,000",
    date: "2026-02-18",
    status: "Pending",
  },
  {
    id: 3,
    campaignName: "Fit India Challenge",
    brand: "ActiveWear Co.",
    influencer: "Beer Biceps",
    budget: "\u20B91,80,000",
    date: "2026-02-20",
    status: "Declined",
  },
  {
    id: 4,
    campaignName: "Taste of India",
    brand: "SpiceCraft",
    influencer: "Kabita Singh",
    budget: "\u20B91,20,000",
    date: "2026-02-22",
    status: "Pending",
  },
]

export const categories = [
  {
    name: "Technology",
    shortName: "Tech",
    count: 85,
    color: "#E94560",
    description: "Gadgets, software, AI & startups",
  },
  {
    name: "Beauty & Skincare",
    shortName: "Beauty",
    count: 120,
    color: "#FF6B81",
    description: "Makeup, skincare routines & reviews",
  },
  {
    name: "Health & Fitness",
    shortName: "Fitness",
    count: 65,
    color: "#00B4D8",
    description: "Workouts, nutrition & wellness tips",
  },
  {
    name: "Food & Cuisine",
    shortName: "Food",
    count: 95,
    color: "#FF9F43",
    description: "Recipes, street food & restaurants",
  },
  {
    name: "Travel & Adventure",
    shortName: "Travel",
    count: 78,
    color: "#10B981",
    description: "Destinations, tips & travel vlogs",
  },
  {
    name: "Fashion & Style",
    shortName: "Fashion",
    count: 110,
    color: "#A855F7",
    description: "Trends, ethnic wear & styling",
  },
  {
    name: "Wellness & Mindfulness",
    shortName: "Wellness",
    count: 42,
    color: "#14B8A6",
    description: "Yoga, meditation & Ayurveda",
  },
  {
    name: "Finance & Investing",
    shortName: "Finance",
    count: 38,
    color: "#3B82F6",
    description: "Stocks, mutual funds & crypto",
  },
]
